spring:
  application:
    name: CoreService
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: stackoverflow-group
    auto-offset-reset: earliest

scheduler:
  check-links: 10s

ml-service:
  base-url: http://localhost:8042